spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}


server:
  port: 8765

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off
